# Generated by Django 5.2.5 on 2025-10-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Nome oficial da empresa', max_length=200, verbose_name='Nome da Empresa')),
                ('logo', models.ImageField(blank=True, help_text='Logo da empresa (formatos: JPG, PNG)', null=True, upload_to='site_config/logos/', verbose_name='Logo')),
                ('phone', models.CharField(help_text='Telefone principal da empresa', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='E-mail de contato principal', max_length=254, verbose_name='E-mail')),
                ('address', models.TextField(help_text='Endereço completo da empresa', verbose_name='Endereço')),
                ('whatsapp', models.CharField(help_text='Número do WhatsApp (apenas números)', max_length=20, verbose_name='WhatsApp')),
                ('facebook_url', models.URLField(blank=True, help_text='URL completa da página do Facebook', null=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, help_text='URL completa do perfil do Instagram', null=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, help_text='URL completa da página do LinkedIn', null=True, verbose_name='LinkedIn')),
                ('hero_title', models.CharField(help_text='Título principal da página inicial', max_length=300, verbose_name='Título Principal')),
                ('hero_subtitle', models.CharField(help_text='Subtítulo da página inicial', max_length=500, verbose_name='Subtítulo')),
                ('about_text', models.TextField(help_text='Texto descritivo sobre a empresa', verbose_name='Texto Sobre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
                'ordering': ['-updated_at'],
            },
        ),
    ]
