# Generated by Django 5.2.5 on 2025-09-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='vehicles/')),
                ('drivers', models.ManyToManyField(related_name='vehicles', to='conductors.driver')),
            ],
        ),
    ]
