# Generated by Django 5.2.5 on 2025-09-10 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductors', '0002_conductor'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['plate'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='drivers',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default='Marca não informada', max_length=50, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Chassi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='conductors',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='conductors.conductor', verbose_name='Condutores'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Gasolina'), ('ethanol', 'Etanol'), ('diesel', 'Diesel'), ('flex', 'Flex'), ('electric', 'Elétrico'), ('hybrid', 'Híbrido')], default='flex', max_length=20, verbose_name='Tipo de Combustível'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='passenger_capacity',
            field=models.PositiveIntegerField(default=5, verbose_name='Capacidade de Passageiros'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='renavam',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='RENAVAM'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='Não informada', max_length=30, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='Modelo não informado', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Ano'),
        ),
    ]
