# Generated by Django 5.2.5 on 2025-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='photo',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Foto 1'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Foto 2'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Foto 3'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Foto 4'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Foto 5'),
        ),
    ]
