# Generated by Django 5.2.5 on 2025-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_photo_vehicle_photo_1_vehicle_photo_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('Van', 'Van'), ('Caminhão', 'Caminhão'), ('Ônibus', 'Ônibus'), ('Carreta', 'Carreta'), ('Carro', 'Carro')], default='Van', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
