# Generated by Django 5.2.5 on 2025-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Nome da empresa exibido no site', max_length=200, verbose_name='Nome da Empresa')),
                ('phone', models.CharField(help_text='Telefone principal da empresa (ex: (11) 1234-5678)', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Email de contato principal', max_length=254, verbose_name='Email')),
                ('address', models.TextField(help_text='Endereço completo da empresa', verbose_name='Endereço')),
                ('whatsapp', models.CharField(blank=True, help_text='Número do WhatsApp (ex: 5511912345678)', max_length=20, null=True, verbose_name='WhatsApp')),
                ('facebook_url', models.URLField(blank=True, help_text='Link completo do Facebook', null=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Link completo do Instagram', null=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='Link completo do LinkedIn', null=True, verbose_name='LinkedIn URL')),
                ('hero_title', models.CharField(help_text='Título principal da landing page (Hero Section)', max_length=255, verbose_name='Título Principal')),
                ('hero_subtitle', models.CharField(blank=True, help_text='Subtítulo da landing page (Hero Section)', max_length=500, null=True, verbose_name='Subtítulo')),
                ('about_text', models.TextField(help_text='Texto descritivo sobre a empresa', verbose_name='Texto Sobre a Empresa')),
                ('logo', models.ImageField(blank=True, help_text='Logo da empresa (formato PNG ou JPG)', null=True, upload_to='site_config/logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
                'db_table': 'site_configuration',
            },
        ),
    ]
