# Generated by Django 5.2.5 on 2025-10-28 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('driver_request', 'Solicitação de Motorista'), ('vehicle_request', 'Solicitação de Veículo')], help_text='Tipo de solicitação que gerou a notificação', max_length=20, verbose_name='Tipo de Notificação')),
                ('request_id', models.IntegerField(help_text='ID da solicitação referenciada', verbose_name='ID da Solicitação')),
                ('title', models.CharField(help_text='Título resumido da notificação', max_length=200, verbose_name='Título')),
                ('message', models.TextField(help_text='Mensagem detalhada da notificação', verbose_name='Mensagem')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Indica se a notificação foi lida', verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, help_text='Data e hora em que foi marcada como lida', null=True, verbose_name='Data de Leitura')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a notificação foi criada', verbose_name='Data de Criação')),
                ('read_by', models.ForeignKey(blank=True, help_text='Usuário que marcou a notificação como lida', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_read', to=settings.AUTH_USER_MODEL, verbose_name='Lida por')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='notificatio_is_read_3a06ff_idx'), models.Index(fields=['notification_type', 'request_id'], name='notificatio_notific_893286_idx')],
            },
        ),
    ]
