# Generated by Django 5.2.5 on 2025-10-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_add_photo_to_driver_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverrequest',
            old_name='cnh_number',
            new_name='license_number',
        ),
        migrations.RenameField(
            model_name='driverrequest',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='driverrequest',
            name='cnh_category',
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Data de nascimento do condutor', null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Cidade do endereço', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='cnh_digital',
            field=models.FileField(blank=True, help_text='CNH digitalizada (opcional)', null=True, upload_to='requests/driver/cnh/', verbose_name='CNH Digital (PDF)'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='document',
            field=models.FileField(blank=True, help_text='Documento de identificação (opcional)', null=True, upload_to='requests/driver/documents/', verbose_name='Documento do Condutor (PDF)'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', help_text='Sexo do condutor', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='license_category',
            field=models.CharField(choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('AB', 'Categoria AB'), ('AC', 'Categoria AC'), ('AD', 'Categoria AD'), ('AE', 'Categoria AE'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E')], default=0, help_text='Categoria da habilitação do condutor', max_length=5, verbose_name='Categoria da CNH'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='license_expiry_date',
            field=models.DateField(blank=True, help_text='Data de validade da CNH', null=True, verbose_name='Validade da CNH'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='nationality',
            field=models.CharField(default='Brasileira', help_text='Nacionalidade do condutor', max_length=50, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='neighborhood',
            field=models.CharField(blank=True, default='', help_text='Bairro do endereço', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='number',
            field=models.CharField(blank=True, default='', help_text='Número do endereço', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='reference_point',
            field=models.CharField(blank=True, help_text='Referência adicional do endereço', max_length=200, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='street',
            field=models.CharField(blank=True, default='', help_text='Rua ou avenida do endereço', max_length=200, verbose_name='Rua/Avenida'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp do condutor (opcional)', max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='driverrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Observações adicionais do solicitante', null=True, verbose_name='Mensagem'),
        ),
    ]
