# Generated by Django 5.2.5 on 2025-10-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_rename_cnh_number_driverrequest_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequest',
            name='category',
            field=models.CharField(choices=[('Van', 'Van'), ('Caminhão', 'Caminhão'), ('Ônibus', 'Ônibus'), ('Carreta', 'Carreta'), ('Carro', 'Carro')], default='Van', help_text='Categoria do veículo', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='chassis_number',
            field=models.CharField(blank=True, default='', help_text='Número do chassi do veículo', max_length=50, verbose_name='Chassi'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='passenger_capacity',
            field=models.PositiveIntegerField(default=5, help_text='Número de passageiros que o veículo comporta', verbose_name='Capacidade de Passageiros'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='photo_1',
            field=models.ImageField(blank=True, help_text='Foto do veículo (opcional)', null=True, upload_to='requests/vehicle/photos/', verbose_name='Foto 1'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='photo_2',
            field=models.ImageField(blank=True, help_text='Foto do veículo (opcional)', null=True, upload_to='requests/vehicle/photos/', verbose_name='Foto 2'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='photo_3',
            field=models.ImageField(blank=True, help_text='Foto do veículo (opcional)', null=True, upload_to='requests/vehicle/photos/', verbose_name='Foto 3'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='photo_4',
            field=models.ImageField(blank=True, help_text='Foto do veículo (opcional)', null=True, upload_to='requests/vehicle/photos/', verbose_name='Foto 4'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='photo_5',
            field=models.ImageField(blank=True, help_text='Foto do veículo (opcional)', null=True, upload_to='requests/vehicle/photos/', verbose_name='Foto 5'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='renavam',
            field=models.CharField(blank=True, default='', help_text='Número do RENAVAM', max_length=20, verbose_name='RENAVAM'),
        ),
    ]
