# Generated by Django 5.2.5 on 2025-10-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_vehiclerequest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequest',
            name='protocol',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Protocolo gerado automaticamente (formato: DRV-YYYYNNNN)', max_length=12, null=True, unique=True, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='protocol',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Protocolo gerado automaticamente (formato: VHC-YYYYNNNN)', max_length=12, null=True, unique=True, verbose_name='Protocolo'),
        ),
    ]
