# Generated by Django 5.2.5 on 2025-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_driverrequest_protocol_vehiclerequest_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequest',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a solicitação foi visualizada pela primeira vez', null=True, verbose_name='Data de Visualização'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a solicitação foi visualizada pela primeira vez', null=True, verbose_name='Data de Visualização'),
        ),
    ]
