# Generated by Django 5.2.5 on 2025-10-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_driverrequest_viewed_at_vehiclerequest_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequest',
            name='crlv_pdf',
            field=models.FileField(blank=True, help_text='Certificado de Registro e Licenciamento de Veículo em PDF (opcional)', null=True, upload_to='requests/vehicle/documents/', verbose_name='CRLV (PDF)'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='insurance_pdf',
            field=models.FileField(blank=True, help_text='Documento do seguro do veículo em PDF (opcional)', null=True, upload_to='requests/vehicle/documents/', verbose_name='Seguro (PDF)'),
        ),
    ]
