# Generated by Django 5.2.5 on 2025-09-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('photo', models.ImageField(upload_to='drivers/')),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
