# Generated by Django 5.2.5 on 2025-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='conductors/', verbose_name='Foto')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='CNH')),
                ('license_category', models.CharField(choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E'), ('AB', 'Categoria A+B'), ('AC', 'Categoria A+C'), ('AD', 'Categoria A+D'), ('AE', 'Categoria A+E')], default='B', max_length=5, verbose_name='Categoria da CNH')),
                ('license_expiry_date', models.DateField(verbose_name='Validade da CNH')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Condutor',
                'verbose_name_plural': 'Condutores',
                'ordering': ['name'],
            },
        ),
    ]
