# Generated by Django 5.2.5 on 2025-09-10 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductors', '0002_conductor'),
        ('vehicles', '0002_alter_vehicle_options_remove_vehicle_drivers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.AddField(
            model_name='conductor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
