# Generated by Django 5.2.5 on 2025-09-10 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductors', '0003_delete_driver_conductor_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_updates', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
    ]
