# Generated by Django 5.2.5 on 2025-09-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductors', '0004_conductor_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='cnh_digital',
            field=models.FileField(blank=True, null=True, upload_to='conductors/cnh/', verbose_name='CNH Digital (PDF)'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='nationality',
            field=models.CharField(default='Brasileira', max_length=50, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='address',
            field=models.TextField(default='', verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='license_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número da CNH'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone/Celular'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='conductors/photos/', verbose_name='Foto da Pessoa'),
        ),
    ]
