# Generated by Django 5.2.5 on 2025-09-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductors', '0005_conductor_cnh_digital_conductor_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='address',
        ),
        migrations.AddField(
            model_name='conductor',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='neighborhood',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='number',
            field=models.CharField(default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='reference_point',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='street',
            field=models.CharField(default='', max_length=200, verbose_name='Rua/Avenida'),
        ),
    ]
