# Generated by Django 5.2.5 on 2025-09-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductors', '0006_remove_conductor_address_conductor_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='photo',
        ),
        migrations.AddField(
            model_name='conductor',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='conductors/documents/', verbose_name='Documento do Condutor (PDF)'),
        ),
    ]
