# Generated by Django 5.2.5 on 2025-10-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductors', '0007_remove_conductor_photo_conductor_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='conductors/photos/', verbose_name='Foto 1 (JPG/PNG)'),
        ),
    ]
