# Generated by Django 5.2.5 on 2025-10-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='complaint',
            name='complaints__priorit_9b6e83_idx',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='priority',
        ),
    ]
