# Generated by Django 5.2.5 on 2025-10-24 17:05

from django.db import migrations, models


def migrate_status_values(apps, schema_editor):
    """
    Migra os valores antigos de status para os novos.
    - pendente -> proposto
    - em_analise -> em_analise (mantém)
    - resolvida -> concluido
    - arquivada -> concluido
    """
    Complaint = apps.get_model('complaints', 'Complaint')

    # Converter status antigos para novos
    Complaint.objects.filter(status='pendente').update(status='proposto')
    Complaint.objects.filter(status='resolvida').update(status='concluido')
    Complaint.objects.filter(status='arquivada').update(status='concluido')


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_priority'),
    ]

    operations = [
        # Primeiro migrar os dados
        migrations.RunPython(migrate_status_values, migrations.RunPython.noop),
        # Depois alterar o campo
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('proposto', 'Proposto'), ('em_analise', 'Em Análise'), ('concluido', 'Concluído')], db_index=True, default='proposto', help_text='Status atual da denúncia', max_length=20, verbose_name='Status'),
        ),
    ]
