# Generated by Django 5.2.5 on 2025-10-24 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_add_protocol_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Foto da denúncia (máximo 5 fotos por denúncia)', upload_to='complaints/photos/%Y/%m/%d/', verbose_name='Foto')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a foto foi enviada', verbose_name='Data do Upload')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição da foto', verbose_name='Ordem')),
                ('complaint', models.ForeignKey(help_text='Denúncia a qual esta foto pertence', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='complaints.complaint', verbose_name='Denúncia')),
            ],
            options={
                'verbose_name': 'Foto da Denúncia',
                'verbose_name_plural': 'Fotos das Denúncias',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
