# Generated by Django 5.2.5 on 2025-12-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_add_complaint_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='occurrence_location',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='protocol',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Protocolo gerado automaticamente (formato: CMP-YYYYNNNN)', max_length=12, null=True, unique=True, verbose_name='Protocolo'),
        ),
    ]
