# Generated by Django 5.2.5 on 2025-12-29 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_complaint_occurrence_location_and_more'),
        ('vehicles', '0006_remove_vehicle_owner_alter_vehicle_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='occurrence_location',
            field=models.CharField(blank=True, help_text='Endereço ou local onde ocorreu o fato denunciado', max_length=200, null=True, verbose_name='Local da Ocorrência'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', help_text='Nível de prioridade da denúncia', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['vehicle_plate', 'status'], name='complaints__vehicle_a18cda_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complaint_type', 'status'], name='complaints__complai_6bf4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['is_anonymous', 'status'], name='complaints__is_anon_2f16e3_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['priority', '-created_at'], name='complaints__priorit_3dcbb4_idx'),
        ),
    ]
