# Generated by Django 5.2.5 on 2026-03-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('approver', 'Aprovador'), ('viewer', 'Visualizador')], db_index=True, default='viewer', max_length=20, verbose_name='Papel'),
        ),
    ]
